### PR TITLE
solved lab

### PR DESCRIPTION
**Pull request by alotaibisara**

### CODE REVIEW

**Comment by AbdulmohsenAlateeq** [comment]
Function should return the number of words.

**Comment by alotaibisara** [comment]
Are you mean the number of index ?

**Comment by AbdulmohsenAlateeq** [comment]
What I meant your function return a string of characters separated by a space, It should return the number of words like what you did in the last line.

**Comment by AbdulmohsenAlateeq** [comment]
Good work Sara.

**Pull request closed without merging**
